<script lang="ts">
	/**
	 * RollToast — Glass popup that surfaces the latest log entry when the
	 * user is on a tab where the session log is not visible (i.e. not Adventure).
	 *
	 * Watches logs[SESSION_LOG_ID][0]. When a new entry arrives and the
	 * current tab is not 'adventure', it fades in at the bottom of the viewport,
	 * then auto-dismisses after AUTO_DISMISS_MS. Notes (entries with `source`)
	 * are suppressed — the user just typed them, no need to echo them back.
	 */

	import { fly, fade } from 'svelte/transition';
	import { logs, SESSION_LOG_ID, type LogEntry } from '$lib/log.svelte.js';
	import { sanitizeLogHtml } from '$lib/sanitize.js';

	const AUTO_DISMISS_MS = 6000;

	let { activeTab }: { activeTab: string } = $props();

	let visible = $state(false);
	let toastEntry = $state<LogEntry | null>(null);
	let _lastSeenId = '';
	let _timer: ReturnType<typeof setTimeout> | undefined;

	// Derive the latest log entry reactively
	const latestEntry = $derived((logs[SESSION_LOG_ID] ?? [])[0] ?? null);

	$effect(() => {
		const entry = latestEntry;
		if (!entry) return;
		if (entry.id === _lastSeenId) return; // already seen
		if (entry.source) {
			_lastSeenId = entry.id;
			return;
		} // skip notes
		// Only surface results on tabs where roll actions exist but the log isn't visible
		if (activeTab !== 'expeditions' && activeTab !== 'communities') {
			_lastSeenId = entry.id;
			return;
		}

		_lastSeenId = entry.id;
		toastEntry = entry;
		visible = true;

		clearTimeout(_timer);
		_timer = setTimeout(dismiss, AUTO_DISMISS_MS);
	});

	function dismiss() {
		clearTimeout(_timer);
		visible = false;
	}
</script>

{#if visible && toastEntry}
	<!-- svelte-ignore a11y_no_static_element_interactions -->
	<div
		class="roll-toast"
		role="status"
		aria-live="polite"
		in:fly={{ y: 24, duration: 220 }}
		out:fade={{ duration: 180 }}
	>
		<div class="rt-header">
			<span class="rt-title">{toastEntry.title}</span>
			<button class="rt-close" onclick={dismiss} aria-label="Dismiss">
				<svg
					xmlns="http://www.w3.org/2000/svg"
					width="13"
					height="13"
					viewBox="0 0 24 24"
					fill="none"
					stroke="currentColor"
					stroke-width="2.5"
					stroke-linecap="round"
					stroke-linejoin="round"
				>
					<line x1="18" y1="6" x2="6" y2="18" />
					<line x1="6" y1="6" x2="18" y2="18" />
				</svg>
			</button>
		</div>
		<div class="rt-body">{@html sanitizeLogHtml(toastEntry.html)}</div>
	</div>
{/if}

<style>
	.roll-toast {
		position: fixed;
		bottom: calc(env(safe-area-inset-bottom, 0px) + 1.25rem);
		left: 50%;
		transform: translateX(-50%);
		z-index: 600;

		width: min(92vw, 360px);
		padding: 0;
		border-radius: 12px;

		/* Liquid glass */
		background: color-mix(in srgb, var(--bg-card) 82%, transparent);
		backdrop-filter: blur(18px) saturate(180%);
		-webkit-backdrop-filter: blur(18px) saturate(180%);
		border: 1px solid rgba(255, 255, 255, 0.12);
		box-shadow:
			0 16px 48px rgba(0, 0, 0, 0.55),
			inset 0 1px 0 rgba(255, 255, 255, 0.15);
	}

	.rt-header {
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: 8px;
		padding: 9px 12px 7px;
		border-bottom: 1px solid rgba(255, 255, 255, 0.08);
	}

	.rt-title {
		font-family: var(--font-ui);
		font-size: 0.68rem;
		font-weight: 700;
		letter-spacing: 0.06em;
		text-transform: uppercase;
		color: var(--text-accent);
		min-width: 0;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}

	.rt-close {
		display: flex;
		align-items: center;
		justify-content: center;
		background: transparent;
		border: none;
		padding: 2px;
		cursor: pointer;
		color: var(--text-dimmer);
		border-radius: 4px;
		flex-shrink: 0;
		line-height: 1;
		transition: color 0.12s;
	}
	.rt-close:hover {
		color: var(--text);
	}

	.rt-body {
		padding: 10px 12px 12px;
		font-family: var(--font-ui);
		font-size: 0.8rem;
		color: var(--text-muted);
		line-height: 1.5;
	}

	/* Styles for content generated by roll functions */
	.rt-body :global(.roll-line) {
		color: var(--text-dimmer);
		font-size: 0.73rem;
		margin-bottom: 2px;
	}
	.rt-body :global(strong) {
		color: var(--text);
		font-weight: 600;
	}
	.rt-body :global(ul) {
		margin: 4px 0 0 1rem;
		padding: 0;
	}
	.rt-body :global(li) {
		margin-bottom: 2px;
	}
	.rt-body :global(div) {
		margin-bottom: 3px;
	}
</style>
