/**
 * Catalogue routes — serves the static game data (assets, moves, oracles).
 *
 * These are read-only and publicly accessible — no auth required.
 * The data is loaded once at startup and cached in memory for the lifetime
 * of the process. Heavy caching headers tell Nginx and the browser to cache
 * aggressively too; the ETag changes only when the data files change
 * (i.e. when a new version is deployed).
 *
 * Game data lives in apps/api/data/ and is bundled with this project.
 * Override the path with CATALOGUE_PATH in .env if needed.
 *
 * Which files feed each entry is driven by data/extensions.manifest.json —
 * generated at build time by scripts/gen-extensions-manifest.mjs from the
 * per-extension metadata in extensions/<id>/extension.json. Adding/removing an
 * expansion's content is a manifest change, not an edit here. (Phase 1: content
 * still lives under DATA_ROOT; the manifest paths are relative to it.)
 */

import type { FastifyPluginAsyncZod } from 'fastify-type-provider-zod';
import type { FastifyRequest, FastifyReply } from 'fastify';
import { readFile } from 'fs/promises';
import { createHash } from 'crypto';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Default: bundled data directory at apps/api/data/.
// __dirname = apps/api/src/routes/  →  ../.. = apps/api/
// Same relative depth from dist/routes/ after build.
// Override with CATALOGUE_PATH in .env for custom layouts.
const DATA_ROOT = process.env['CATALOGUE_PATH'] ?? path.resolve(__dirname, '../../data');

// Repo root — extensions/ live here (repo-relative). The whole repo is deployed
// (git clone, cwd = repo root), so extension content resolves at runtime.
// __dirname = apps/api/{src,dist}/routes/  →  ../../../.. = repo root.
const REPO_ROOT = path.resolve(__dirname, '../../../..');
/** Content root that still lives under DATA_ROOT (base/delve, Phase 1 layout). */
const LEGACY_ROOT = 'apps/api/data';

/** Resolve a manifest `provides` path against its extension's repo-relative root. */
function resolveContent(root: string, rel: string): string {
  // The legacy data root honours the CATALOGUE_PATH override; everything else
  // (self-contained extensions/<id>/…) is repo-relative.
  const base = root === LEGACY_ROOT ? DATA_ROOT : path.join(REPO_ROOT, root);
  return path.join(base, rel);
}

// ---------------------------------------------------------------------------
// Load data files once at startup
// ---------------------------------------------------------------------------

interface CatalogueEntry {
  data: unknown;
  etag: string;
}

async function loadJson(filePath: string): Promise<unknown> {
  const raw = await readFile(filePath, 'utf-8');
  return JSON.parse(raw);
}

function makeEtag(data: unknown): string {
  return createHash('md5').update(JSON.stringify(data)).digest('hex').slice(0, 16);
}

/** One content type an extension can provide, keyed by the merged catalogue. */
type ProvidesType =
  | 'assets'
  | 'moves'
  | 'moveOverrides'
  | 'oracles'
  | 'foes'
  | 'foeOverrides'
  | 'rollTables'
  | 'delveTables';

interface ExtensionManifestEntry {
  id: string;
  name: string;
  description: string;
  defaultEnabled: boolean;
  order: number;
  /** Repo-relative content root (e.g. `apps/api/data` or `extensions/yrt`). */
  root: string;
  /** Content files this extension provides, relative to `root`. */
  provides?: Partial<Record<ProvidesType, string[]>>;
}

interface ExtensionsManifest {
  extensions: ExtensionManifestEntry[];
}

/** `delve/delve-theme-features.json` → `themeFeatures`. */
function delveKey(rel: string): string {
  return path
    .basename(rel, '.json')
    .replace(/^delve-/, '')
    .replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}

async function loadCatalogue(): Promise<{
  assets: CatalogueEntry;
  moves: CatalogueEntry;
  oracles: CatalogueEntry;
  foes: CatalogueEntry;
  rollTables: CatalogueEntry;
  delve: CatalogueEntry;
  extensions: CatalogueEntry;
}> {
  // The manifest (generated by scripts/gen-extensions-manifest.mjs) is the
  // single source of truth for which files feed each catalogue entry. Each
  // extension declares a repo-relative `root`; base/delve still live under
  // DATA_ROOT, self-contained extensions (e.g. yrt) under extensions/<id>/.
  const manifest = (await loadJson(
    path.join(DATA_ROOT, 'extensions.manifest.json'),
  )) as ExtensionsManifest;
  const extensions = [...manifest.extensions].sort((a, b) => a.order - b.order);

  /** {root, rel} for a content type across every extension, in extension order. */
  const filesFor = (type: ProvidesType): Array<{ root: string; rel: string }> =>
    extensions.flatMap((e) => (e.provides?.[type] ?? []).map((rel) => ({ root: e.root, rel })));
  /** Load every file for a content type, resolving each against its root. */
  const loadAll = (type: ProvidesType): Promise<unknown[]> =>
    Promise.all(filesFor(type).map(({ root, rel }) => loadJson(resolveContent(root, rel))));

  // Assets — merge each file's assets + rarities.
  const assetData = (await loadAll('assets')) as Array<{
    assets: unknown[];
    rarities?: unknown[];
  }>;
  const allAssets = {
    assets: assetData.flatMap((f) => f.assets),
    rarities: assetData.flatMap((f) => f.rarities ?? []),
  };

  // Moves — flatten each file's moves; each moveOverrides file carries one
  // expansion's present/absent patches against the base move catalogue
  // (mirrors the foe override mechanism below).
  const moveData = (await loadAll('moves')) as Array<{ moves: unknown[] }>;
  const allMoves = {
    moves: moveData.flatMap((f) => f.moves),
    overrides: await loadAll('moveOverrides'),
  };

  // Oracles — one table per file.
  const allOracles = { oracles: await loadAll('oracles') };

  // Roll-tables — "resolver oracles" (d100 → foe/asset). One table per file.
  const allRollTables = { tables: await loadAll('rollTables') };

  // Foes — merge foe lists; each foeOverrides file carries one expansion's
  // present/absent + addendum patches against the base foe catalogue.
  const foeData = (await loadAll('foes')) as Array<{ foes: unknown[] }>;
  const allFoes = {
    foes: foeData.flatMap((f) => f.foes),
    overrides: await loadAll('foeOverrides'),
  };

  // Delve theme/domain tables — a keyed object, one key per file.
  const delveFiles = filesFor('delveTables');
  const delveTables = await Promise.all(
    delveFiles.map(({ root, rel }) => loadJson(resolveContent(root, rel))),
  );
  const allDelve = Object.fromEntries(
    delveFiles.map(({ rel }, i) => [delveKey(rel), delveTables[i]]),
  );

  return {
    assets: { data: allAssets, etag: makeEtag(allAssets) },
    moves: { data: allMoves, etag: makeEtag(allMoves) },
    oracles: { data: allOracles, etag: makeEtag(allOracles) },
    foes: { data: allFoes, etag: makeEtag(allFoes) },
    rollTables: { data: allRollTables, etag: makeEtag(allRollTables) },
    delve: { data: allDelve, etag: makeEtag(allDelve) },
    // Public extension registry — metadata only (drop the file lists). Drives
    // the client's dynamic expansion toggles + source labels.
    extensions: (() => {
      const list = extensions.map(({ id, name, description, defaultEnabled, order }) => ({
        id,
        name,
        description,
        defaultEnabled,
        order,
      }));
      return { data: list, etag: makeEtag(list) };
    })(),
  };
}

// ---------------------------------------------------------------------------
// Route plugin
// ---------------------------------------------------------------------------

export const catalogueRoutes: FastifyPluginAsyncZod = async (server) => {
  // Load once when the plugin registers
  const catalogue = await loadCatalogue();

  function sendCatalogueItem(
    entry: CatalogueEntry,
    req: FastifyRequest,
    reply: FastifyReply,
  ): void {
    // Return 304 Not Modified if the client already has this version
    if (req.headers['if-none-match'] === entry.etag) {
      reply.status(304).send();
      return;
    }

    reply
      .header('ETag', entry.etag)
      .header(
        'Cache-Control',
        process.env.NODE_ENV === 'production'
          ? 'public, max-age=3600, stale-while-revalidate=86400'
          : 'no-store',
      )
      .status(200)
      .send(entry.data);
  }

  server.get('/assets', (req, reply) => sendCatalogueItem(catalogue.assets, req, reply));
  server.get('/moves', (req, reply) => sendCatalogueItem(catalogue.moves, req, reply));
  server.get('/oracles', (req, reply) => sendCatalogueItem(catalogue.oracles, req, reply));
  server.get('/foes', (req, reply) => sendCatalogueItem(catalogue.foes, req, reply));
  server.get('/roll-tables', (req, reply) => sendCatalogueItem(catalogue.rollTables, req, reply));
  server.get('/delve', (req, reply) => sendCatalogueItem(catalogue.delve, req, reply));
  server.get('/extensions', (req, reply) => sendCatalogueItem(catalogue.extensions, req, reply));
};
