/**
 * Catalogue routes — serves the static game data (assets, moves, oracles).
 *
 * These are read-only and publicly accessible — no auth required.
 * The data is loaded once at startup and cached in memory for the lifetime
 * of the process. Heavy caching headers tell Nginx and the browser to cache
 * aggressively too; the ETag changes only when the data files change
 * (i.e. when a new version is deployed).
 *
 * Game data lives in apps/api/data/ and is bundled with this project.
 * Override the path with CATALOGUE_PATH in .env if needed.
 *
 * Which files feed each entry is driven by data/extensions.manifest.json —
 * generated at build time by scripts/gen-extensions-manifest.mjs from the
 * per-extension metadata in extensions/<id>/extension.json. Adding/removing an
 * expansion's content is a manifest change, not an edit here. (Phase 1: content
 * still lives under DATA_ROOT; the manifest paths are relative to it.)
 */

import type { FastifyPluginAsyncZod } from 'fastify-type-provider-zod';
import type { FastifyRequest, FastifyReply } from 'fastify';
import { readFile } from 'fs/promises';
import { createHash } from 'crypto';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Default: bundled data directory at apps/api/data/.
// __dirname = apps/api/src/routes/  →  ../.. = apps/api/
// Same relative depth from dist/routes/ after build.
// Override with CATALOGUE_PATH in .env for custom layouts.
const DATA_ROOT = process.env['CATALOGUE_PATH'] ?? path.resolve(__dirname, '../../data');

// ---------------------------------------------------------------------------
// Load data files once at startup
// ---------------------------------------------------------------------------

interface CatalogueEntry {
  data: unknown;
  etag: string;
}

async function loadJson(filePath: string): Promise<unknown> {
  const raw = await readFile(filePath, 'utf-8');
  return JSON.parse(raw);
}

function makeEtag(data: unknown): string {
  return createHash('md5').update(JSON.stringify(data)).digest('hex').slice(0, 16);
}

/** One content type an extension can provide, keyed by the merged catalogue. */
type ProvidesType = 'assets' | 'moves' | 'oracles' | 'foes' | 'foeOverrides' | 'delveTables';

interface ExtensionManifestEntry {
  id: string;
  name: string;
  description: string;
  defaultEnabled: boolean;
  order: number;
  /** Content files this extension provides, relative to DATA_ROOT (Phase 1). */
  provides?: Partial<Record<ProvidesType, string[]>>;
}

interface ExtensionsManifest {
  extensions: ExtensionManifestEntry[];
}

/** `delve/delve-theme-features.json` → `themeFeatures`. */
function delveKey(rel: string): string {
  return path
    .basename(rel, '.json')
    .replace(/^delve-/, '')
    .replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}

async function loadCatalogue(): Promise<{
  assets: CatalogueEntry;
  moves: CatalogueEntry;
  oracles: CatalogueEntry;
  foes: CatalogueEntry;
  delve: CatalogueEntry;
}> {
  // The manifest (generated by scripts/gen-extensions-manifest.mjs) is the
  // single source of truth for which files feed each catalogue entry. Content
  // still lives in DATA_ROOT (Phase 1); the manifest just lists it, grouped by
  // extension and ordered so the merge is deterministic.
  const manifest = (await loadJson(
    path.join(DATA_ROOT, 'extensions.manifest.json'),
  )) as ExtensionsManifest;
  const extensions = [...manifest.extensions].sort((a, b) => a.order - b.order);

  /** All files for a content type across every extension, in extension order. */
  const filesFor = (type: ProvidesType): string[] =>
    extensions.flatMap((e) => e.provides?.[type] ?? []);
  /** Load every file for a content type. */
  const loadAll = (type: ProvidesType): Promise<unknown[]> =>
    Promise.all(filesFor(type).map((rel) => loadJson(path.join(DATA_ROOT, rel))));

  // Assets — merge each file's assets + rarities.
  const assetData = (await loadAll('assets')) as Array<{
    assets: unknown[];
    rarities?: unknown[];
  }>;
  const allAssets = {
    assets: assetData.flatMap((f) => f.assets),
    rarities: assetData.flatMap((f) => f.rarities ?? []),
  };

  // Moves — flatten each file's moves.
  const moveData = (await loadAll('moves')) as Array<{ moves: unknown[] }>;
  const allMoves = { moves: moveData.flatMap((f) => f.moves) };

  // Oracles — one table per file.
  const allOracles = { oracles: await loadAll('oracles') };

  // Foes — merge foe lists; each foeOverrides file carries one expansion's
  // present/absent + addendum patches against the base foe catalogue.
  const foeData = (await loadAll('foes')) as Array<{ foes: unknown[] }>;
  const allFoes = {
    foes: foeData.flatMap((f) => f.foes),
    overrides: await loadAll('foeOverrides'),
  };

  // Delve theme/domain tables — a keyed object, one key per file.
  const delveFiles = filesFor('delveTables');
  const delveTables = await Promise.all(
    delveFiles.map((rel) => loadJson(path.join(DATA_ROOT, rel))),
  );
  const allDelve = Object.fromEntries(delveFiles.map((rel, i) => [delveKey(rel), delveTables[i]]));

  return {
    assets: { data: allAssets, etag: makeEtag(allAssets) },
    moves: { data: allMoves, etag: makeEtag(allMoves) },
    oracles: { data: allOracles, etag: makeEtag(allOracles) },
    foes: { data: allFoes, etag: makeEtag(allFoes) },
    delve: { data: allDelve, etag: makeEtag(allDelve) },
  };
}

// ---------------------------------------------------------------------------
// Route plugin
// ---------------------------------------------------------------------------

export const catalogueRoutes: FastifyPluginAsyncZod = async (server) => {
  // Load once when the plugin registers
  const catalogue = await loadCatalogue();

  function sendCatalogueItem(
    entry: CatalogueEntry,
    req: FastifyRequest,
    reply: FastifyReply,
  ): void {
    // Return 304 Not Modified if the client already has this version
    if (req.headers['if-none-match'] === entry.etag) {
      reply.status(304).send();
      return;
    }

    reply
      .header('ETag', entry.etag)
      .header(
        'Cache-Control',
        process.env.NODE_ENV === 'production'
          ? 'public, max-age=3600, stale-while-revalidate=86400'
          : 'no-store',
      )
      .status(200)
      .send(entry.data);
  }

  server.get('/assets', (req, reply) => sendCatalogueItem(catalogue.assets, req, reply));
  server.get('/moves', (req, reply) => sendCatalogueItem(catalogue.moves, req, reply));
  server.get('/oracles', (req, reply) => sendCatalogueItem(catalogue.oracles, req, reply));
  server.get('/foes', (req, reply) => sendCatalogueItem(catalogue.foes, req, reply));
  server.get('/delve', (req, reply) => sendCatalogueItem(catalogue.delve, req, reply));
};
