// =============================================================================
// Settlement kit — culture presets (PROTOTYPE)
//
// Named Design overrides + a matching palette for the peoples of the YRT
// setting. Grounded in the foe entries (apps/api/data/foes, extensions/delve
// foes, and their YRT addenda in extensions/yrt/foes/overrides.json), plus
// docs/verdani.md and oracles/religion.json. Dwarves have no YRT lore, so
// they get the classic stone-hold treatment. Merged over DEFAULT_DESIGN.
// =============================================================================

/** @typedef {import('./pieces3d.mjs').Design} Design */
/** @typedef {{wall: string, roof: string, wood: string, earth: string, water: string, ink: string, flag: string, halo: string}} Palette */
/** @typedef {{note: string, design: Partial<Design>, palette: Palette}} Culture */

/** @type {Record<string, Culture>} */
export const CULTURES = {
	Dwarves: {
		note: 'Squat stone holds: masonry walls, slit windows, crenellated towers, smithies everywhere.',
		design: {
			stature: 0.72,
			scale: 1.05,
			masonry: true,
			pitch: 0.5,
			concave: 0,
			gable: 0.2,
			storeys: 0.1,
			window: 'slit',
			towerRoof: 'crenel',
			spire: 1.4,
			taper: 0.12,
			flags: true,
			flagFolds: 1,
			wall: 'stone',
			wallH: 1.35,
			merlons: true,
			wallTowers: 6,
			gate: 'twin',
			wallShape: 'square',
			industry: 0.6,
			church: false,
			symbol: 'none',
			keep: 'all',
			market: 'town',
			flourish: 0.1,
		},
		palette: {
			wall: '#D6CFC1',
			roof: '#6B6F78',
			wood: '#8A6A48',
			earth: '#8C8068',
			water: '#8FB0B8',
			ink: '#2B2622',
			flag: '#9C3B2A',
			halo: '#F2EEE6',
		},
	},
	Verdani: {
		note: 'The elves of YRT: grown round houses on the green-mana preserves, swept roofs, living hedges, amber banners, the Wildens wheel.',
		design: {
			houseForm: 'round',
			stature: 1.1,
			pitch: 1.05,
			concave: 0.28,
			gable: 0.8,
			storeys: 0.2,
			window: 'round',
			towerRoof: 'cone',
			spire: 3.2,
			taper: 0.15,
			flags: true,
			flagFolds: 4,
			flagLen: 15,
			wall: 'hedge',
			wallShape: 'round',
			church: true,
			symbol: 'wheel',
			keep: 'none',
			market: 'none',
			industry: 0,
			flourish: 0.5,
		},
		palette: {
			wall: '#EDE6CF',
			roof: '#6E8B4E',
			wood: '#5F7F45',
			earth: '#7C8A55',
			water: '#8FB0B8',
			ink: '#2E2A20',
			flag: '#C08A2E',
			halo: '#F3F0E2',
		},
	},
	Giants: {
		note: 'The Jokul: herders of oxen, goats and sheep in hard winters — a few huge Norse longhouses with crossed horn-gables, round huts among them, no walls, keeps or markets.',
		design: {
			houseForm: 'timber',
			longhouse: 0.75,
			huts: 0.35,
			scale: 1.6,
			stature: 1.3,
			pitch: 1,
			depth: 1.1,
			concave: 0,
			gable: 0.1,
			storeys: 0,
			window: 'slit',
			towerRoof: 'cone',
			flags: false,
			wall: 'none',
			church: false,
			symbol: 'none',
			keep: 'none',
			market: 'none',
			industry: 0,
			flourish: 0,
			masonry: false,
		},
		palette: {
			wall: '#D9CBB0',
			roof: '#9A7B58',
			wood: '#7D6448',
			earth: '#7E7458',
			water: '#8FB0BC',
			ink: '#2F2A24',
			flag: '#5C4A3A',
			halo: '#F2EDE2',
		},
	},
	Varou: {
		note: 'Wolf-folk of the deep woods who value territory above all: steep longhouses behind a stake palisade, beaded ornament, long war-banners, clan marks clawed into the posts.',
		design: {
			pitch: 1.1,
			depth: 1.1,
			concave: 0.05,
			gable: 0.1,
			longhouse: 0.6,
			storeys: 0,
			window: 'slit',
			towerRoof: 'cone',
			spire: 1.6,
			flags: true,
			flagFolds: 1,
			flagLen: 15,
			wall: 'palisade',
			wallShape: 'round',
			gate: 'tower',
			church: false,
			symbol: 'claw',
			keep: 'none',
			market: 'town',
			industry: 0.1,
			flourish: 0.4,
			scale: 1.1,
		},
		palette: {
			wall: '#E3D6BF',
			roof: '#7A5A3C',
			wood: '#8B6A44',
			earth: '#7A6A48',
			water: '#8FA8B0',
			ink: '#2A221B',
			flag: '#8E2A22',
			halo: '#F2EBDD',
		},
	},
	Trolls: {
		note: 'Solitary, shy hoarders with camouflaging skin: a few turf mounds far apart, each one a hiding place for the hoard — no walls, shrines or market.',
		design: {
			houseForm: 'mound',
			scale: 1.7,
			stature: 0.85,
			pitch: 0.6,
			window: 'round',
			towerRoof: 'crenel',
			flags: false,
			wall: 'none',
			church: false,
			symbol: 'none',
			keep: 'none',
			market: 'none',
			industry: 0,
			flourish: 0,
		},
		palette: {
			wall: '#CFC6B0',
			roof: '#6F7A55',
			wood: '#7A6A50',
			earth: '#6F7A55',
			water: '#8FB0B8',
			ink: '#2B2A24',
			flag: '#4B4A3A',
			halo: '#EEEADF',
		},
	},
	Buralia: {
		note: 'Grass and high plateau: round thatched huts inside earth banks, streamers in the red of Buralia, the twelve-spoked Wildens wheel.',
		design: {
			houseForm: 'round',
			pitch: 1.2,
			concave: 0.05,
			window: 'square',
			towerRoof: 'cone',
			spire: 2,
			flags: true,
			flagFolds: 4,
			flagLen: 13,
			wall: 'earth',
			wallShape: 'round',
			gate: 'tower',
			church: true,
			symbol: 'wheel',
			keep: 'none',
			market: 'town',
			industry: 0.15,
			flourish: 0.3,
		},
		palette: {
			wall: '#EFE3C6',
			roof: '#C9A55C',
			wood: '#9C7A4C',
			earth: '#8E9A5A',
			water: '#8FB0B8',
			ink: '#3A2D1E',
			flag: '#B3312A',
			halo: '#F6EEDC',
		},
	},
	Nysis: {
		note: 'Puritan and ornate — the country of the flourish: onion domes, finials, ridge cresting, banners in Nysian gold on every tower.',
		design: {
			flourish: 1,
			concave: 0.18,
			pitch: 0.95,
			gable: 0.8,
			storeys: 0.6,
			window: 'arched',
			manyDoors: true,
			towerRoof: 'onion',
			spire: 2.8,
			taper: 0.05,
			flags: true,
			flagFolds: 4,
			flagLen: 15,
			wall: 'stone',
			wallH: 1.1,
			merlons: true,
			wallTowers: 6,
			gate: 'twin',
			wallShape: 'round',
			industry: 0.25,
			church: true,
			symbol: 'sun',
			keep: 'city',
			market: 'town',
		},
		palette: {
			wall: '#F3EBDD',
			roof: '#3F6FA8',
			wood: '#B08A5A',
			earth: '#8A9060',
			water: '#8FB0B8',
			ink: '#2B2633',
			flag: '#D9A92B',
			halo: '#F8F3EA',
		},
	},
	Ostrea: {
		note: 'A Nysis whaling city: onion domes like the rest of Nysis, but a fence of whale ribs, a jawbone gate, whaling warehouses and a busy market.',
		design: {
			flourish: 0.6,
			concave: 0.12,
			pitch: 0.9,
			gable: 0.6,
			storeys: 0.5,
			window: 'arched',
			towerRoof: 'onion',
			spire: 2.4,
			flags: true,
			flagFolds: 3,
			wall: 'bone',
			gate: 'jawbone',
			wallShape: 'round',
			industry: 0.5,
			church: true,
			symbol: 'horns',
			keep: 'none',
			market: 'all',
		},
		palette: {
			wall: '#EFE9DE',
			roof: '#4F7F8A',
			wood: '#8F7A62',
			earth: '#7F8A6A',
			water: '#8FB0B8',
			ink: '#26302F',
			flag: '#D9A92B',
			halo: '#F5F2EA',
		},
	},
	Mososi: {
		note: 'Optime and plain — a plain sentence in answer to a flourish: straight roofs, square windows, masonry, and only the plain green flag of Mososi.',
		design: {
			flourish: 0,
			concave: 0,
			pitch: 0.7,
			gable: 0.4,
			storeys: 0.4,
			window: 'square',
			manyDoors: false,
			towerRoof: 'cone',
			spire: 1.8,
			flags: true,
			flagFolds: 1,
			flagLen: 11,
			wall: 'stone',
			merlons: false,
			wallShape: 'square',
			gate: 'tower',
			wallTowers: 4,
			church: true,
			symbol: 'orb',
			keep: 'city',
			market: 'town',
			industry: 0.35,
			masonry: true,
		},
		palette: {
			wall: '#ECE7DD',
			roof: '#A0523D',
			wood: '#9A7B57',
			earth: '#8C8460',
			water: '#8FB0B8',
			ink: '#33302C',
			flag: '#3E7A44',
			halo: '#F6F2EA',
		},
	},
	Merrow: {
		note: 'Semiaquatic and zealous: stilt huts over a salt lagoon behind a jagged reef, shrines to the deep gods under a trident — no markets, no traffic with outsiders.',
		design: {
			houseForm: 'stilt',
			ground: 'water',
			stature: 0.95,
			pitch: 1.05,
			concave: 0.22,
			window: 'round',
			towerRoof: 'cone',
			spire: 2.4,
			flags: false,
			wall: 'reef',
			wallShape: 'round',
			church: false,
			symbol: 'trident',
			keep: 'none',
			market: 'none',
			industry: 0,
			flourish: 0.2,
		},
		palette: {
			wall: '#DCE3DD',
			roof: '#3E6E6A',
			wood: '#6B6A55',
			earth: '#6E7F78',
			water: '#7FA9AC',
			ink: '#1F2A2E',
			flag: '#5B7F3A',
			halo: '#EEF3EF',
		},
	},
};
